apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: 22i2463-mern-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: noorulain26/docker-mern-nginx-bezkoder-api-1:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URL
          value: "mongodb://mongodb-service:27017/bezkoder_db"
        - name: DB_URL
          value: "mongodb://mongodb-service:27017/bezkoder_db"
        - name: NODE_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: 22i2463-mern-app
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 6868
      targetPort: 8080
      nodePort: 30300
