apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: 22i2463-mern-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: noorulain26/docker-mern-nginx-bezkoder-ui-1:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: 22i2463-mern-app
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 8888
      targetPort: 80
      nodePort: 30173
